use anyhow::{bail, Result};
use colored::Colorize;
use dialoguer::{theme::ColorfulTheme, Confirm};
use std::fs;
use std::io::IsTerminal;
use std::path::PathBuf;

const INTEGRATION_MARKER: &str = "stax shell-setup";

/// The shell function block that users source in their shell config.
/// It intercepts worktree create/go flows for both `st` and `stax`, performs
/// the actual `cd` in the calling shell process, and can safely relocate the
/// shell before removing the current worktree.
fn shell_snippet() -> &'static str {
    r#"# Generated by stax shell-setup
export STAX_SHELL_INTEGRATION=1

__stax_insert_shell_output() {
  local out=()
  local inserted=0
  local arg

  for arg in "$@"; do
    if [[ $inserted -eq 0 && "$arg" == "--" ]]; then
      out+=("--shell-output")
      inserted=1
    fi
    out+=("$arg")
  done

  if [[ $inserted -eq 0 ]]; then
    out+=("--shell-output")
  fi

  printf '%s\0' "${out[@]}"
}

__stax_run_worktree_shell() {
  local raw
  local path=""
  local launch=""
  local cmd=()
  local item

  while IFS= read -r -d '' item; do
    cmd+=("$item")
  done < <(__stax_insert_shell_output "$@")

  raw=$(command stax "${cmd[@]}") || return $?

  while IFS= read -r line; do
    case "$line" in
      STAX_SHELL_PATH=*) path="${line#STAX_SHELL_PATH=}" ;;
      STAX_SHELL_LAUNCH=*) launch="${line#STAX_SHELL_LAUNCH=}" ;;
    esac
  done <<< "$raw"

  if [[ -n "$path" ]]; then
    builtin cd "$path" || return 1
  fi

  if [[ -n "$launch" ]]; then
    eval "$launch"
  elif [[ -n "$path" ]]; then
    echo "$(tput bold)$(tput setaf 6)~$(tput sgr0) $(basename "$path")"
  fi
}

__stax_remove_current_worktree() {
  local current
  local main
  current=$(pwd -P)
  main=$(git worktree list --porcelain 2>/dev/null | sed -n 's/^worktree //p' | head -n1)

  if [[ -n "$main" && -d "$main" ]]; then
    builtin cd "$main" || return 1
  fi

  command stax "$@" "$current"
}

__stax_dispatch() {
  case "$1" in
    wtgo)
      __stax_run_worktree_shell worktree go "${@:2}" ;;
    wtc)
      __stax_run_worktree_shell worktree create "${@:2}" ;;
    wtrm)
      if [[ -z "$2" || "$2" == -* ]]; then
        __stax_remove_current_worktree worktree remove "${@:2}"
      else
        command stax "$@"
      fi ;;
    worktree|wt)
      case "$2" in
        go|create|c)
          __stax_run_worktree_shell "$@" ;;
        remove|rm)
          if [[ -z "$3" || "$3" == -* ]]; then
            __stax_remove_current_worktree "$@"
          else
            command stax "$@"
          fi ;;
        *)
          command stax "$@" ;;
      esac ;;
    *)
      command stax "$@" ;;
  esac
}

# Existing aliases break zsh function definitions, so clear them first.
unalias stax 2>/dev/null || true
unalias st 2>/dev/null || true
unalias sw 2>/dev/null || true
stax() { __stax_dispatch "$@"; }
st() { __stax_dispatch "$@"; }
sw() { st wt go "$@"; }"#
}

/// Print the shell snippet to stdout (for `eval "$(stax shell-setup)"`).
pub fn run(install: bool) -> Result<()> {
    if install {
        install_to_shell_config()
    } else {
        println!("{}", shell_snippet());
        Ok(())
    }
}

/// Returns true if `STAX_SHELL_INTEGRATION` is set in the environment,
/// which means the shell function has been sourced.
pub fn is_installed() -> bool {
    std::env::var("STAX_SHELL_INTEGRATION").is_ok()
}

/// If shell integration is not installed and we're in an interactive terminal,
/// offer to install it. Silent in non-interactive contexts.
pub fn prompt_if_missing() -> Result<()> {
    if is_installed() {
        return Ok(());
    }
    if !std::io::stdin().is_terminal() {
        return Ok(());
    }

    eprintln!("{} Shell integration not detected.", "stax:".cyan().bold());
    eprintln!(
        "  Run {} for transparent worktree navigation (cd).",
        "stax shell-setup --install".cyan()
    );
    eprintln!();

    let install = Confirm::with_theme(&ColorfulTheme::default())
        .with_prompt("Install shell integration now?")
        .default(true)
        .interact()?;

    if install {
        install_to_shell_config()?;
        eprintln!();
        eprintln!(
            "{}  Restart your shell or run: {}",
            "Done.".green().bold(),
            shell_source_cmd().cyan()
        );
        eprintln!();
    }

    Ok(())
}

fn install_to_shell_config() -> Result<()> {
    let config_path = detect_shell_config()?;
    let eval_line = format!("eval \"$({})\"", INTEGRATION_MARKER);

    let existing = if config_path.exists() {
        fs::read_to_string(&config_path)?
    } else {
        String::new()
    };

    if existing.lines().any(|l| l.contains(INTEGRATION_MARKER)) {
        println!(
            "{}  Already present in {}",
            "OK".green().bold(),
            config_path.display()
        );
        return Ok(());
    }

    println!("Will append to {}:", config_path.display());
    println!();
    println!("  {}", eval_line.cyan());
    println!();

    let proceed = Confirm::with_theme(&ColorfulTheme::default())
        .with_prompt("Proceed?")
        .default(true)
        .interact()?;

    if !proceed {
        println!("{}", "Aborted.".dimmed());
        return Ok(());
    }

    let suffix = if existing.is_empty() || existing.ends_with('\n') {
        format!("{}\n", eval_line)
    } else {
        format!("\n{}\n", eval_line)
    };

    fs::write(&config_path, format!("{}{}", existing, suffix))?;

    println!(
        "{}  Added to {}",
        "Done.".green().bold(),
        config_path.display()
    );
    println!("  Restart your shell or run: {}", shell_source_cmd().cyan());

    Ok(())
}

fn detect_shell_config() -> Result<PathBuf> {
    let shell = std::env::var("SHELL").unwrap_or_default();
    let home = std::env::var("HOME").unwrap_or_default();

    if home.is_empty() {
        bail!("$HOME is not set; cannot detect shell config file.");
    }

    let path = if shell.ends_with("zsh") {
        PathBuf::from(&home).join(".zshrc")
    } else if shell.ends_with("bash") {
        // Prefer .bash_profile on macOS, .bashrc on Linux
        let profile = PathBuf::from(&home).join(".bash_profile");
        if cfg!(target_os = "macos") && !profile.exists() {
            PathBuf::from(&home).join(".bashrc")
        } else if cfg!(target_os = "macos") {
            profile
        } else {
            PathBuf::from(&home).join(".bashrc")
        }
    } else if shell.ends_with("fish") {
        PathBuf::from(&home).join(".config/fish/config.fish")
    } else {
        // Fallback to .profile
        PathBuf::from(&home).join(".profile")
    };

    Ok(path)
}

fn shell_source_cmd() -> String {
    if let Ok(shell) = std::env::var("SHELL") {
        let config = detect_shell_config().unwrap_or_else(|_| PathBuf::from("~/.zshrc"));
        if shell.ends_with("fish") {
            return format!("source {}", config.display());
        }
        return format!("source {}", config.display());
    }
    "source ~/.zshrc".to_string()
}

#[cfg(test)]
mod tests {
    use super::shell_snippet;

    #[test]
    fn shell_snippet_clears_aliases_before_function_definitions() {
        let snippet = shell_snippet();

        let unalias_stax = snippet.find("unalias stax").expect("missing stax unalias");
        let unalias_st = snippet.find("unalias st ").expect("missing st unalias");
        let unalias_sw = snippet.find("unalias sw").expect("missing sw unalias");
        let stax_fn = snippet.find("stax()").expect("missing stax function");
        let st_fn = snippet.find("st()").expect("missing st function");
        let sw_fn = snippet.find("sw()").expect("missing sw function");

        assert!(unalias_stax < stax_fn);
        assert!(unalias_st < st_fn);
        assert!(unalias_sw < sw_fn);
    }
}
